################################################################################
# Re-factored Automatically-generated file. Generated by Atmel Studio 7
################################################################################

COMPILER := arm-none-eabi-
CC := $(COMPILER)gcc
AR := $(COMPILER)ar

RM := rm -rf

C_SRCS :=  \
atmel_start.c \
Device_Startup/startup_samd21.c \
Device_Startup/system_samd21.c \
board/hal/hal.c \
driver_init.c \
examples/driver_examples.c \
hal/src/hal_atomic.c \
hal/src/hal_delay.c \
hal/src/hal_ext_irq.c \
hal/src/hal_flash.c \
hal/src/hal_gpio.c \
hal/src/hal_i2c_m_sync.c \
hal/src/hal_init.c \
hal/src/hal_io.c \
hal/src/hal_sleep.c \
hal/src/hal_usb_device.c \
hal/utils/src/utils_assert.c \
hal/utils/src/utils_event.c \
hal/utils/src/utils_list.c \
hal/utils/src/utils_syscalls.c \
hpl/core/hpl_core_m0plus_base.c \
hpl/core/hpl_init.c \
hpl/dmac/hpl_dmac.c \
hpl/eic/hpl_eic.c \
hpl/gclk/hpl_gclk.c \
hpl/nvmctrl/hpl_nvmctrl.c \
hpl/pm/hpl_pm.c \
hpl/rtc/rtc_lite.c \
hpl/sercom/hpl_sercom.c \
hpl/spi/spi_lite.c \
hpl/sysctrl/hpl_sysctrl.c \
hpl/usb/hpl_usb.c \
main.c \
persistent_storage/nv_internal_flash_ultra.c \
persistent_storage/nv_storage.c \
persistent_storage_start.c \
usb/class/cdc/device/cdcdf_acm.c \
usb/device/usbdc.c \
usb/usb_protocol.c \
usb_start.c

OBJDIR := build
C_SRCSDIR := .

INC := -I$(C_SRCSDIR)/packs/CMSIS/Core/Include \
       -I$(C_SRCSDIR)/packs/samd21a/include \
       -I$(C_SRCSDIR)/Config \
       -I$(C_SRCSDIR) \
       -I$(C_SRCSDIR)/examples \
       -I$(C_SRCSDIR)/hal/include \
       -I$(C_SRCSDIR)/hal/utils/include \
       -I$(C_SRCSDIR)/hpl/core \
       -I$(C_SRCSDIR)/hpl/dmac \
       -I$(C_SRCSDIR)/hpl/eic \
       -I$(C_SRCSDIR)/hpl/gclk \
       -I$(C_SRCSDIR)/hpl/nvmctrl \
       -I$(C_SRCSDIR)/hpl/pm \
       -I$(C_SRCSDIR)/hpl/port \
       -I$(C_SRCSDIR)/hpl/rtc \
       -I$(C_SRCSDIR)/hpl/sercom \
       -I$(C_SRCSDIR)/hpl/spi \
       -I$(C_SRCSDIR)/hpl/sysctrl \
       -I$(C_SRCSDIR)/hpl/usb \
       -I$(C_SRCSDIR)/hri \
       -I$(C_SRCSDIR)/include \
       -I$(C_SRCSDIR)/usb \
       -I$(C_SRCSDIR)/usb/class/cdc \
       -I$(C_SRCSDIR)/usb/class/cdc/device \
       -I$(C_SRCSDIR)/usb/device \
       -I$(C_SRCSDIR)/persistent_storage
       
CFLAGS := -x c -mthumb -D__SAMD21G18A__ -DNDEBUG $(INC) -Os -ffunction-sections -mlong-calls -Wall -mcpu=cortex-m0plus -std=gnu99   

_OBJS := $(patsubst %.c,%.o,$(C_SRCS))
OBJS := $(addprefix $(OBJDIR)/, $(_OBJS))

OUTPUT_FILE_PATH := $(OBJDIR)/libfeather_m0_lora_driver.a
    
# All Target
all: $(OUTPUT_FILE_PATH)

# AVR32/GNU C Compiler
$(OBJS): $(OBJDIR)/%.o: $(C_SRCSDIR)/%.c
	mkdir -p $(@D)
	@echo Building file: $<
	@echo Invoking: ARM/GNU C Compiler : 6.3.1
	$(CC) -c $(CFLAGS) -o "$@" "$<" 
	@echo Finished building: $<

$(OUTPUT_FILE_PATH): $(OBJS)
	@echo Building target: $@
	@echo Invoking: ARM/GNU Archiver : 6.3.1
	$(AR) -r  -o $(OUTPUT_FILE_PATH) $(OBJS)
	@echo Finished building target: $@
	
# Other Targets
clean:
	$(RM) $(OBJS) 
	$(RM) $(OUTPUT_FILE_PATH)
	